name: yc_app_utils
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  cached_network_image:  3.3.0
  dropdown_search: 5.0.6
  flutter:
    sdk: flutter
  flutter_svg: 2.0.10+1
  flutter_form_builder: 9.4.1
  intl: 0.19.0
  flutter_bootstrap: 2.0.0
  carousel_slider: 5.0.0
  shimmer: 3.0.0
  lottie: 3.1.2
  visibility_detector: 0.4.0+2
  vibration: 2.0.0
  mask_text_input_formatter: ^2.9.0
  http: 1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/Nunito-Regular.ttf
    - family: Nunito-Bold
      fonts:
        - asset: assets/fonts/Nunito/Nunito-Bold.ttf
    - family: Nunito-Semi
      fonts:
        - asset: assets/fonts/Nunito/Nunito-SemiBold.ttf
    - family: Nunito-ExtraBold
      fonts:
        - asset: assets/fonts/Nunito/Nunito-ExtraBold.ttf
    - family: Roboto-Slab
      fonts:
        - asset: assets/fonts/RobotoSlab/RobotoSlab.ttf
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
